### ISSUE TITLE
Name change

### ISSUE THREAD

**Issue by aleaf** [aleaf/SFRmaker#86]
Guys, since it seems like the name of this package has converged to SFRmaker (or at least that's what most people seem to call it), I've changed the repository name to reflect this. Let me know if you have any issues with this!

Note that this also means that the upstream url for your forks has changed. You can update your local repositories to reflect this by running this at the command line or git bash:

```
$ git remote set-url origin new_url
```

**Comment by aleaf** [comment]
The new url is <https://github.com/aleaf/SFRmaker/>

**Comment by hwreeves-USGS** [comment]
sounds good, thanks Andy-

HWR

Howard W. Reeves
USGS Michigan Water Science Center
6520 Mercantile Way, Suite 5
Lansing, MI 48911-5991
517-887-8914
517-887-8937 (fax)
hwreeves@usgs.gov

**Comment by pjuckem** [comment]
I know you're all better with git than I am, but in the off chance that you sink to my level for just one moment, keep in mind that when updating a fork of this repo, use "upstream" instead of "origin".  

$ git remote set-url upstream new_url

Learn from my mistakes...
Paul

**Comment by aleaf** [comment]
my bad, I believe you are right. Sorry about that!
