### ISSUE TITLE
Repository Cleanup

### ISSUE THREAD

**Issue by aleaf** [aleaf/SFRmaker#90]
Guys,
I went ahead and did some house cleaning of the main folder in the repo. I moved everything to an "archive" folder, except the Arcmap **.lyr** files, which I moved to a symbology folder. I didn't delete anything. I thought it would be good to clear away everything that is superseded, or that duplicates an example file (e.g. all of the SFR_main and XML input files we had in there). Let me know if you have any objections; we can of course always roll anything back.

**Comment by hwreeves-USGS** [comment]
good idea Andy - thanks -
HWR

Howard W. Reeves
USGS Michigan Water Science Center
6520 Mercantile Way, Suite 5
Lansing, MI 48911-5991
517-887-8914
517-887-8937 (fax)
hwreeves@usgs.gov
