### ISSUE TITLE
Trouble importing SFRMaker

### ISSUE THREAD

**Issue by hwreeves-USGS** [aleaf/SFRmaker#94]
I am getting an error importing SFRMaker, although I have installed GIS-Utils, I am getting an error on __init__ saying 

---> 12 from sfrmaker import Lines, StructuredGrid
     13 from sfrmaker.utils import assign_layers
     14 import GISio as GISio

f:\projects\sfrmaker\sfrmaker\__init__.py in <module>
      1 from ._version import get_versions
----> 2 from .gis import crs
      3 from .grid import StructuredGrid, UnstructuredGrid
      4 from .lines import Lines
      5 from .mf5to6 import mf6sfr

f:\projects\sfrmaker\sfrmaker\gis.py in <module>
      9 from shapely.geometry import shape, Polygon, box
     10 from shapely.ops import unary_union
---> 11 from gisutils import get_proj_str, df2shp, shp2df, project
     12 
     13 

ModuleNotFoundError: No module named 'gisutils'

But  I can import the GISio and GISops components of gisutils
from GISio import shp2df, get_proj4

I'm not running from the SFRmaker environment - conda is throwing an error when I try to create the environment:

Downloading and Extracting Packages
m2w64-gettext-0.19.7 | 4.2 MB    |                                                                              |   0%

CondaHTTPError: HTTP 500 INTERNAL ERROR for url <https://repo.anaconda.com/pkgs/msys2/win-64/m2w64-gettext-0.19.7-2.tar.bz2>
Elapsed: 00:33.499060

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

**Comment by aleaf** [comment]
@hwreeves-USGS, I think there are a few issues here.

1) For better or worse, I've essentially deprecated the [GIS_utils project](https://github.com/aleaf/GIS_utils) (with the GISio and GISops modules) and replaced it with [gis-utils](https://github.com/aleaf/gis-utils), which has a cleaner project structure based on the [scientific-python-cookiecutter](https://github.com/NSLS-II/scientific-python-cookiecutter) and automated testing. So anything related to `GIS_utils` should be independent of the import issue you are having.

2) Unless importing fails on your machine with the environment in `requirements.yml`, I think this is most likely an issue with your python environment. The [test suite](https://github.com/aleaf/SFRmaker/tree/master/sfrmaker/test) imports sfrmaker and gisutils, so an import problem with sfrmaker itself (assuming the required dependencies are installed) is unlikely. 

3) The issue you mention with `m2w64-gettext-0.19.7` has been a reoccurring problem for the last several months. It seems to have something to do with the USGS network. I've added [some documentation](https://github.com/aleaf/SFRmaker/blob/master/Installing_dependencies.md) with workarounds to get past this issue.

**Comment by hwreeves-USGS** [comment]
thanks Andy - I'm using the old project right now, so I will move to gis-utils.

HWR


Howard W. Reeves
Groundwater and Watershed Modeling Team Lead
USGS Upper Midwest Water Science Center
5840 Enterprise Drive
Lansing, Michigan 48911
517-887-8914
________________________________
