### ISSUE TITLE
Issue with NHDFlowlines attribute table headers

### ISSUE THREAD

**Issue by RyanConway91** [aleaf/sfrmaker#96]
I was getting the error:

  File "C:\Anaconda3\lib\site-packages\sfrmaker\nhdplus_utils.py", line 125, in load_nhdplus_v2
    df = fl[fl_cols].copy()
    ...
    ...
KeyError: "['GNIS_NAME', 'LENGTHKM', 'COMID'] not in index"

Looking at my NHDFlowlines.dbf, I have the field names:
['GNIS_Name', 'LengthKM', 'ComID'] 

I added 2 lines in nhdplus_utils.py
```
# join flowline and attribute dataframes , line 122
fl.columns = [c.upper() for c in list(fl)] #added this, switch all to upper case
fl = fl.rename(columns = {"GEOMETRY":"geometry"})#added this (switch GEOMETRY back to lower case)
```
To fix the issue

**Comment by aleaf** [comment]
Hey @RyanConway91, thanks for bringing this to my attention. This should be fixed with 8634869b.
