### ISSUE TITLE
Need to include unrouted cells in MF6 connections data block

### ISSUE THREAD

**Issue by mnfienen** [aleaf/sfrmaker#98]
It's a bit of a pathological case, but in some cases (like the edge of a model) a single cell may be included in the SFR network but not be routed to another cell. Currently, in such cases, nothing is written to the connectiondata block, but the cells needs to be included in connectiondata but with no other entry on the line for routing. Not including these unrouted cells will cause more recent versions of MF6 to bomb.

**Comment by aleaf** [comment]
this should be fixed by 90afdd08c2d66

**Comment by mnfienen** [comment]
thanks @aleaf !
